server:
    port: 8080
    servlet:
        context-path: "/api/v1"

logging:
    level:
        org.hibernate: trace

spring:
  servlet:
    multipart:
     max-file-size: 100000000

  datasource:
    username: market
    password: market
    url: jdbc:mysql://localhost:3306/Market
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
          ddl-auto: update
      show-sql: true
      database: mysql

filestore:
    root: "C:\\GitRepos\\Mplace\\Back\\MarketBackend\\files"

jwt:
  expirationMs: 18000000
  secret: "FreeonlinetoolforHMACcomputationandcalculationwithcryptographichashfunctionsuch"
  cookieName: "apiToken"
