service:
  name: "My Marketplace"
  email: "aaa@ss.dd"
  url: "http://localhost:8080"

signup:
  wipe-interval: 30
  token-timeout-mins: 30

server:
    port: 8080
    servlet:
        context-path: "/api/v1"

logging:
    level:
        org.hibernate: off
        org.springframework.security: info

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env, health

spring:
  config:
    import: classpath:database.yml, classpath:jwt.yml #, classpath:email.yml

  servlet:
    multipart:
     max-file-size: 100000000

filestore:
    root: "C:\\GitRepos\\Mplace\\Back\\MarketBackend\\files"








