server:
    port: 8080
    servlet:
        context-path: "/api/v1"

logging:
    level:
        org.hibernate: off

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env, health

spring:
  config:
    import: classpath:email.yml, classpath:database.yml, classpath:jwt.yml

  servlet:
    multipart:
     max-file-size: 100000000

filestore:
    root: "C:\\GitRepos\\Mplace\\Back\\MarketBackend\\files"








