service:
  name: "My Marketplace"
  email: "aaa@ss.dd"
  url: "https://localhost:8443"

signup:
  wipe-interval: 30
  token-timeout-mins: 30

scheduling:
  enabled: true

logging:
    level:
        org.hibernate: off
        org.springframework.security: info

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env, health

spring:
  profiles:
    active: "dev"

  config:
    import: classpath:database.yml, classpath:jwt.yml, classpath:serverprops.yml #, classpath:email.yml

  servlet:
    multipart:
     max-file-size: 100000000

filestore:
    root: "C:\\GitRepos\\Mplace\\Back\\MarketBackend\\files"








